openapi: 3.0.0
info:
  title: Simple Recipe API
  description: This is a simple API for Concetta's Recipes
  contact:
    email: concetta_m_jester@homedepot.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/JOHNEWHITLEY_1/Concettas-Recipes/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /recipe/{recipeId}:
    get:
      summary: Find recipe by ID
      description: Returns a single recipe
      operationId: getRecipeById
      parameters:
      - name: recipeId
        in: path
        description: ID of recipe to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
            application/xml:
              schema:
                $ref: '#/components/schemas/Recipe'
        "400":
          description: Invalid ID supplied
        "404":
          description: Recipe not found
      x-swagger-router-controller: Default
  /recipe:
    post:
      summary: adds a recipe item
      description: Adds a recipe to the system
      operationId: addRecipe
      requestBody:
        description: Recipe to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        "201":
          description: recipe created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing recipe already exists
      x-swagger-router-controller: Default
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        ingredients:
          type: array
          items:
            type: string
      description: Recipe schema
      example:
        name: name
        ingredients:
        - ingredients
        - ingredients
        id: 0
